name: uhoh
description: A simple tool to backup GitHub repos.
version: 1.1.0
homepage: https://github.com/TravisWheelerLab/uhoh

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.6.0
  github: ^6.1.0
  logging: ^0.11.4
  meta: ^1.1.8
  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.14.0
